name: Deploy AWS


on:
  push: 
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      packages: write

    steps:
     - name: Checkout code
       uses: actions/checkout@v4
       
     - name: Set up Python
       uses: actions/setup-python@v5
       with: 
        python-version: '3.11'

     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: "danieljuhokim"
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
       
     - name: Build and push
       uses: docker/build-push-action@v5
       with:
         context: .
         file: ./Dockerfile
         push: true
         tags: danieljuhokim/docker_movimentacao_test:${{ github.sha }}

     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.HOST_TEST }}
        username: "ubuntu"
        key: ${{ secrets.KEY_TEST }}
        port: 22
        script: |
          docker stop app_python_movimentacoes
          docker rm --force app_python_movimentacoes
          docker run -d -p 8081:5000 --name app_python_movimentacoes danieljuhokim/docker_movimentacao_test:${{ github.sha }}
